spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgresql
    url: jdbc:postgresql://akiswolepsuasw:99e5bcaf5ab52b62a0600d7fc384e3bca4ca62f11d2839235dc1aa035f173bb3@ec2-54-243-28-109.compute-1.amazonaws.com:5432/d18sseh8c36epr
    driverClassName: org.postgresql.Driver